name: Build with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adoptopenjdk'  # You can use 'adoptopenjdk' or any other distribution that supports JDK 23.

      # Install dependencies and build with Gradle
      - name: Build with Gradle
        run: ./gradlew build
