name: Enhanced Appium Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['23', '17']
        node-version: ['18', '16']
        os: ['ubuntu-latest', 'windows-latest'] # Test on multiple operating systems
      max-parallel: 4 #tests in parallel across matrix

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java (Matrix)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: gradle

      # Step 3: Set up Node.js (Matrix)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 4: Install Appium
      - name: Install Appium
        run: npm install -g appium

      # Step 5: Start Appium Server
      - name: Start Appium Server
        run: appium --port 4723 &

      # Step 6: Install Dependencies
      - name: Install Gradle Dependencies
        run: ./gradlew dependencies

      # Step 7: Run Tests
      - name: Run Tests
        run: ./gradlew clean test

      # Step 8: Save Test Artifacts
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: build/screenshots/

      # Step 9: Save Logs
      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: appium-logs
          path: /tmp/appium-logs/

  notify-results:
    needs: run-tests
    runs-on: ubuntu-latest
    if: failure()
    steps:
      # Notify on Failure (Slack Integration)
      - name: Send Failure Notification to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text": "The Appium test workflow failed on ${{ matrix.os }} using Java ${{ matrix.java-version }} and Node.js ${{ matrix.node-version }}. Check the Actions tab for details."}' \
            https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK

      # Notify on Failure (Email Integration)
      - name: Send Failure Notification to Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Appium Test Workflow Failed"
          body: "The Appium workflow failed. Check the logs for details."
          to: "team@example.com"
          from: "ci@example.com"
